#  here we will create config file of project 
artifacts_root: artifacts

#  once the pipeline is triggred in root_dir path data_ingestion file is created ,download data from source url , 
# save in local_data_file path in zip format , after unziping ( extraction) save it to   unzip_dir
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE:  artifacts/data_validation/status.txt