#  here we will create config file of project 
artifacts_root: artifacts

#  once the pipeline is triggred in root_dir path data_ingestion file is created ,download data from source url , 
# save in local_data_file path in zip format , after unziping ( extraction) save it to   unzip_dir
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE:  artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

data_training:
  root_dir: artifacts/data_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/data_training/model.joblib
  metrics_file_name: artifacts/model_evaluation/metrics.json